spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:54321/blog
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        format_sql: true

azure:
  storage:
    container:
      name: blog-images
    connection:
      string: ${connection_string}


logging:
  level:
    org:
      springframework:
        security: DEBUG